retryConfig:
    type: simple
    maxAttempts: 3
    waitBeforeNextAttemptMs: 1000

#api-key: e9b4ba7c9154
haConfigs:

  - methodName: GetDeviceList
    httpMethod: GET
    #прод
    urlTemplate: http://172.16.30.29:8080/v1/device_list?user_id=${user_id}
    #тест
    #urlTemplate: http://217.73.58.41:8080/v1/device_list?user_id=${user_id}
    headers:
      #прод
      api-key: test_key
      #тест
      #api-key: e9b4ba7c9154
    parameters: [user_id]

  - methodName: setMeters
    httpMethod: POST
    #прод
    urlTemplate: http://172.16.30.29:8080/v1/indication
    #тест
    #urlTemplate: http://217.73.58.41:8080/v1/indication
    headers:
      Content-Type: application/json
      #прод
      api-key: test_key
      #тест
      #api-key: e9b4ba7c9154
    parameters: [counter_id, date, vl_indicator]
    bodyTemplate: |
        {
          "counter_id": "${counter_id}",
          "date": "${date}",
          "session_id": 0,
          "vl_indicator": "${vl_indicator}"
        }